export type ActionBarMenuType = {
	back?: boolean;
	edit?: boolean;
	view?: boolean;
	switch?: boolean;
	save?: boolean;
	create?: boolean;
	createDisabled?: boolean;
	project?: boolean;
	search?: boolean;
	getState?: boolean;
	getStateDisabled?: boolean;
	setState?: boolean;
	setStateDisabled?: boolean;
	removeState?: boolean;
	removeStateDisabled?: boolean;
	initialState?: boolean;
	initialStateDisabled?: boolean;
	codeEditor?: boolean;
	upload?: boolean;
	refresh?: boolean;
	interval?: boolean;
	import?: boolean;
	importDisabled?: boolean;
	remove?: boolean;
	detail?: boolean;
	editTitle?: boolean;
	roles?: boolean;
	label?:boolean;
};
