export const dataTypeEnum = [
    'numeric',
    'numeric[]',
    'bit',
    'bit[]',
    'bit varying',
    'bit varying[]',
    'character',
    'character[]',
    'character varying',
    'character varying[]',
    'interval',
    'interval[]',
    'bigserial',
    'serial',
    'smallserial',
    'aclitem',
    'aclitem[]',
    'bigint',
    'bigint[]',
    'boolean',
    'boolean[]',
    'box',
    'box[]',
    'bytea',
    'bytea[]',
    'char',
    'char[]',
    'cid',
    'cid[]',
    'cidr',
    'cidr[]',
    'circle',
    'circle[]',
    'date',
    'date[]',
    'datemultirange',
    'datemultirange[]',
    'daterange',
    'daterange[]',
    'double precision',
    'double precision[]',
    'gtsvector',
    'gtsvector[]',
    'inet',
    'inet[]',
    'int2vector',
    'int2vector[]',
    'int4multirange',
    'int4multirange[]',
    'int4range',
    'int4range[]',
    'int8multirange',
    'int8miltirange[]',
    'int8range',
    'int8range[]',
    'integer',
    'integer[]',
    'json',
    'json[]',
    'jsonb',
    'jsonb[]',
    'jsonpath',
    'jsonpath[]',
    'line',
    'line[]',
    'lseg',
    'lseg[]',
    'macaddr',
    'macaddr[]',
    'macaddr8',
    'macaddr8[]',
    'money',
    'money[]',
    'name',
    'name[]',
    'numrange',
    'numrange[]',
    'nummultirange',
    'nummultirange[]',
    'oid',
    'oid[]',
    'oidvector',
    'oidvector[]',
    'path',
    'path[]',
    'pg_brin_bloom_summary',
    'pg_brin_minmax_multi_summary',
    'pg_dependencies',
    'pg_lsn',
    'pg_lsn[]',
    'pg_ndistinct',
    'pg_node_tree',
    'pg_snapshot',
    'pg_snapshot[]',
    'point',
    'point[]',
    'polygon',
    'polygon[]',
    'real',
    'real[]',
    'refcursor',
    'refcursor[]',
    'regclass',
    'regclass[]',
    'regcollation',
    'regcollation[]',
    'regconfig',
    'regconfig[]',
    'regdictionary',
    'regdictionary[]',
    'regnamespace',
    'regnamespace[]',
    'regoper',
    'regoper[]',
    'regoperator',
    'regoperator[]',
    'regproc',
    'regproc[]',
    'regprocedure',
    'regprocedure[]',
    'regrole',
    'regrole[]',
    'regtype',
    'regtype[]',
    'smallint',
    'smallint[]',
    'text',
    'text[]',
    'tid',
    'tid[]',
    'timestamp with time zone',
    'timestamp with time zone[]',
    'timestamp without time zone',
    'timestamp without time zone[]',
    'time with time zone',
    'time with time zone[]',
    'time without time zone',
    'time without time zone[]',
    'tsmultirange',
    'tsmultirange[]',
    'tsquery',
    'tsquery[]',
    'tsrange',
    'tsrange[]',
    'tstzrange',
    'tstzrange[]',
    'tstzmultirange',
    'tstzmultirange[]',
    'tsvector',
    'tsvector[]',
    'txid_snapshot',
    'txid_snapshot[]',
    'uuid',
    'uuid[]',
    'xid',
    'xid[]',
    'xid8',
    'xid8[]',
    'xml',
    'xml[]',
];

export const dataTypeEnumWithAll = ['numeric', 'numeric[]'];

export const dataTypeWithLengthNoScale = [
    'bit',
    'bit[]',
    'bit varying',
    'bit varying[]',
    'character',
    'character[]',
    'character varying',
    'character varying[]',
    'interval',
    'interval[]',
];

export const dataTypeNoLengthNoDefault = ['bigserial', 'serial', 'smallserial'];

export const dataTypeNoLengthWithDefault = [
    'aclitem',
    'aclitem[]',
    'bigint',
    'bigint[]',
    'boolean',
    'boolean[]',
    'box',
    'box[]',
    'bytea',
    'bytea[]',
    'char',
    'char[]',
    'cid',
    'cid[]',
    'cidr',
    'cidr[]',
    'circle',
    'circle[]',
    'date',
    'date[]',
    'datemultirange',
    'datemultirange[]',
    'daterange',
    'daterange[]',
    'double precision',
    'double precision[]',
    'gtsvector',
    'gtsvector[]',
    'inet',
    'inet[]',
    'int2vector',
    'int2vector[]',
    'int4multirange',
    'int4multirange[]',
    'int4range',
    'int4range[]',
    'int8multirange',
    'int8miltirange[]',
    'int8range',
    'int8range[]',
    'integer',
    'integer[]',
    'json',
    'json[]',
    'jsonb',
    'jsonb[]',
    'jsonpath',
    'jsonpath[]',
    'line',
    'line[]',
    'lseg',
    'lseg[]',
    'macaddr',
    'macaddr[]',
    'macaddr8',
    'macaddr8[]',
    'money',
    'money[]',
    'name',
    'name[]',
    'numrange',
    'numrange[]',
    'nummultirange',
    'nummultirange[]',
    'oid',
    'oid[]',
    'oidvector',
    'oidvector[]',
    'path',
    'path[]',
    'pg_brin_bloom_summary',
    'pg_brin_minmax_multi_summary',
    'pg_dependencies',
    'pg_lsn',
    'pg_lsn[]',
    'pg_ndistinct',
    'pg_node_tree',
    'pg_snapshot',
    'pg_snapshot[]',
    'point',
    'point[]',
    'polygon',
    'polygon[]',
    'real',
    'real[]',
    'refcursor',
    'refcursor[]',
    'regclass',
    'regclass[]',
    'regcollation',
    'regcollation[]',
    'regconfig',
    'regconfig[]',
    'regdictionary',
    'regdictionary[]',
    'regnamespace',
    'regnamespace[]',
    'regoper',
    'regoper[]',
    'regoperator',
    'regoperator[]',
    'regproc',
    'regproc[]',
    'regprocedure',
    'regprocedure[]',
    'regrole',
    'regrole[]',
    'regtype',
    'regtype[]',
    'smallint',
    'smallint[]',
    'text,',
    'text[]',
    'tid',
    'tid[]',
    'timestamp with time zone',
    'timestamp with time zone[]',
    'timestamp without time zone',
    'timestamp without time zone[]',
    'time with time zone',
    'time with time zone[]',
    'time without time zone',
    'time without time zone[]',
    'tsmultirange',
    'tsmultirange[]',
    'tsquery',
    'tsquery[]',
    'tsrange',
    'tsrange[]',
    'tstzrange',
    'tstzrange[]',
    'tstzmultirange',
    'tstzmultirange[]',
    'tsvector',
    'tsvector[]',
    'txid_snapshot',
    'txid_snapshot[]',
    'uuid',
    'uuid[]',
    'xid',
    'xid[]',
    'xid8',
    'xid8[]',
    'xml',
    'xml[]',
];
